### ISSUE TITLE
What if git origin doesn't exist?

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/grade_runner#18]
https://github.com/firstdraft/grade_runner/blob/b653fe5ad02a6bb78b9bbfba40ab8b077533099c/lib/tasks/grade.rake#L57

What if there is no origin, for whatever reason?

**Comment by murugan-r** [comment]
If there is no origin, then github status api call will fail since the build object created doesn't have info.
I guess we need to add validation for username and reponame for build class.

**Comment by jelaniwoods** [comment]
Resolved in https://github.com/firstdraft/grade_runner/commit/4e596648aa4b98415b0ba85734de90eac39b14d1
