### ISSUE TITLE
Hiding grades.yml

### ISSUE THREAD

**Issue by raghubetina** [firstdraft/grade_runner#30]
Is it true on repl.it that _all_ hidden files are not viewable to the public? Or is `.env` exceptional?

If it's true that all hidden files are private, then we should consider making `grades.yml` hidden to protect tokens.

We should then add another command, something like `rake fixtoken`, to overwrite `.grades.yml`.

**Comment by raghubetina** [comment]
This may or may not be necessary anymore on Codio. Please check whether a) Codio workspaces are visible to students, b) even if they do share them with one another, can they see hidden files (I assume that yes, if they share a workspace then hidden files are visible)?

**Comment by jelaniwoods** [comment]
@raghubetina It looks like you _can_ share Codio workspaces. I think by default they are available to Teachers. The settings are available in Project > Permissions.... You can choose to share with all teachers or all students or individual students. You then can further specify Read/Write/Admin access.

It looks like even just with read access will give the shared student the ability to see all files.

**Comment by raghubetina** [comment]
@jelaniwoods Alright; in that case it seems like this issue is pointless; no need to make grades.yml a hidden file, it won't do any good. Right?

**Comment by jelaniwoods** [comment]
@raghubetina yes it seems like all files are visible to anyone with read access—even hidden files.
