### ISSUE TITLE
Show the error message when "error occurred outside of examples" happens

### ISSUE THREAD

**Issue by jelaniwoods** [firstdraft/grade_runner#44]

**Comment by jelaniwoods** [comment]
@raghubetina I've narrowed this down to the `json_output_formatter`. I was wondering how you imagined the error message being in the interface?

To have the same behavior as other failing tests (where you click on a test name and a modal pops up), would require some updating to Grades.

With just changing the formatter, the message can be put in the title, but it's kind of long.

<img width="708" alt="Screen Shot 2020-11-30 at 4 06 21 PM" src="https://user-images.githubusercontent.com/17581658/100671634-6cad4280-3326-11eb-9292-b1ab27a9c4db.png">

--- 

<img width="960" alt="Screen Shot 2020-11-30 at 4 10 12 PM" src="https://user-images.githubusercontent.com/17581658/100671705-89497a80-3326-11eb-944b-cd6d1bab0fd7.png">

Since it's HTML, newlines aren't really being respected yet.

Before I make any changes to Grades, I guess I just wanted to have a better idea of what you were looking for.

**Comment by raghubetina** [comment]
@jelaniwoods IMO this seems like a fairly rare occurrence, so I think just changing the title would be sufficient — it would at least aid us in diagnosing quickly. Do you agree?
