### ISSUE TITLE
Ability to sync local tests to the upstream version

### ISSUE THREAD

**Issue by jelaniwoods** [firstdraft/grade_runner#54]
Whenever there's a bug or unclear test message that we want to update after students have already started we can't affect students spec files (unless we do something fancy like write a script that re-writes their spec file and have them run a command that downloads and runs it haha)

One approach is updating Grades to actually run the tests server side like Ruby Gym does. 

Another, quicker to implement approach is to have `rails grade` check to see if the local spec folder/files are up to date with the latest version stored on appdev-projects/upstream version. If they do match, the normail `rails grade` thing happens. If they don't match, the updated files are downloaded and _then_ the specs are run and submitted to Grades.

This way, students still just run `rails grade` and if we need to make an update, they just have to run `rails grade` again and not some funky command that we make up each time.

Maybe the YAML file can specify what repo to look at (in case we need to customize), but by default it uses appdev-projects org.

**Comment by jelaniwoods** [comment]
@raghubetina what do you think about this proposal?

**Comment by demostudent18** [comment]
Sounds good to me. Are you thinking of comparing timestamps to see if they match? Or what other strategy?

**Comment by raghubetina** [comment]
@jelaniwoods Sounds good to me. It's not immediately obvious to me how to compare to see whether the tests are up to date — timestamps from the GitHub API?

**Comment by raghubetina** [comment]
This SO thread shows promise:

https://stackoverflow.com/questions/4150296/git-how-to-check-for-remote-changes-within-a-directory

**Comment by jelaniwoods** [comment]
> Are you thinking of comparing timestamps to see if they match?

@raghubetina timestamps could work. I was thinking about using Git commit SHA's somehow.

**Comment by jelaniwoods** [comment]
> This SO thread shows promise:
> 
> https://stackoverflow.com/questions/4150296/git-how-to-check-for-remote-changes-within-a-directory

nice!

**Comment by raghubetina** [comment]
Here's another: https://stackoverflow.com/questions/3792989/how-to-view-diff-of-a-forked-github-project/3793113#3793113

**Comment by raghubetina** [comment]
Both are close but not quite. What we really need is to be able to get the SHA digest of a subfolder from GitHub's API, but I don't think that exists.

**Comment by jelaniwoods** [comment]
> Both are close but not quite. What we really need is to be able to get the SHA digest of a subfolder from GitHub's API, but I don't think that exists.

Would it be sufficient to check the upstream repo's latest commit and then see if the local repo contains that commit?

**Comment by raghubetina** [comment]
But what if the new commit upstream modified something other than `spec/`?

I guess it's not the end of the world; then grade_runner would unnecessarily download `spec/` even though it hasn't changed locally.

Next question: how to (force) clone only the `spec/` folder (so as not to conflict with other changes the student has made)?

Leads:

- https://stackoverflow.com/a/56483582/18668061  (requires a new dependency)
- https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository (complicated, I don't quite understand it yet)
