### ISSUE TITLE
Wrong specs copied to student project

### ISSUE THREAD

**Issue by bpurinton** [firstdraft/grade_runner#79]
A student showed me the following scenario:

- They entered a `rake grade` token from a prior project (https://github.com/appdev-projects/sinatra-dice-dynamic) into another project (https://github.com/appdev-projects/sinatra-dice-form)
- The specs for the earlier project were copied over to the spec folder of the current project (notably, both spec files are `spec/features/dice_spec.rb`)
- After resetting the token with `rake grade:reset_token` and re-running `rake grade` with the correct token, the spec file remained as the prior project, rather than being updated with the upstream current project's spec file.
- We fixed the problem by discarding the uncommitted changes to the `dice_spec.rb` file, which reverted the file back to the version delivered with the current project (previously it was stuck with the prior project's file contents, which were delivered by the first incorrect running of `rake grade` with the prior project's token).

I didn't think something like this _could_ even occur, because I thought that each time `rake grade` was run, it looked for the upstream spec files and copied those over to prevent student modifications of our specs.

I will try to re-create the full scenario myself to see if the above steps are indeed exactly what happened (it was a little hard to tell for sure).

cc @jelaniwoods, does this sound like something that might / could have happened?

**Comment by jelaniwoods** [comment]
>  I thought that each time rake grade was run, it looked for the upstream spec files and copied those over to prevent student modifications of our specs.

It _should_ do that, assuming a valid token was provided. If the spec files had been staged but not committed maybe they wouldn't be removed? We might only remove unstaged or committed spec files.

**Comment by bpurinton** [comment]
>  If the spec files had been staged but not committed maybe they wouldn't be removed

I recreated the scenario and that's exactly what occurred.

- The first time running `grade` with the incorrect token pulled in the prior spec file and staged but did not commit it.
- Running `grade:reset_token` and `grade` again with the incorrect token did not pull down the new (i.e. original) spec file
- Making a commit on the old spec file and then running `grade` once more did bring down the original spec file and resolved things.

I'm a bit shocked no student has reported this before, as it seems like an easy mistake to make.

This seems to be related to https://github.com/firstdraft/grade_runner/issues/78?

It seems like the fix to both that issue and this one lies in some updates of the various `git` commands in this method?

https://github.com/firstdraft/grade_runner/blob/beae22e05f5d65349b61891b4f85da73d8829f23/lib/tasks/grade.rake#L134-L158

**Comment by bpurinton** [comment]
Just to re-iterate from standup -- in my testing I did not stage the new (incorrect) spec file that was pulled from the wrong repo, somehow the file was downloaded and staged itself by the `sync_specs_with_source` (perhaps)
